### PR TITLE
Removed Unwanted Center Widget

### PR DESCRIPTION
**Pull request by KABILAN235**
Removed Unwanted Center Widget, which was responsible for Unwanted Behaviour of the GlassContainer Widget in Some Layouts like GridView, Wrap,etc

### CODE REVIEW

**Comment by bharat-1809** [comment]
Hi @KABILAN235 👋🏻
Thanks for opening an issue!  
Can you share a screenshot of the problem for a better understanding?

**Comment by KABILAN235** [comment]
Hi!

So before the Edit, The App Looks Like This

Screenshot 2021-06-15 at 5 42 11 PM

As You Can See Some Glass Widgets are Centred. The "Add" Button Was Actually A Floating Action Button, Location Set to Bottom, But It Appears at the Middle.

Behind The Add Button, There are Some Elements to Represent Chips, To Be Arranged in a Row, using the Wrap Layout, But It Was Aligned Vertically, As Seen.

Code for widgets

Floating Action Button
Screenshot 2021-06-15 at 5 49 09 PM

Applying the Fix, The App Looks Much Better

 
Screenshot 2021-06-15 at 6 48 56 PM

Everything Works Fine.

I Just Modified the Pub Cache to fix this Issue, Just Had an Idea to Update The Main Package, I am New To This Github Stuff, Just Looked up YouTube on How to Suggest Changes. Sorry if Something Went Wrong.

Kabilan

**Comment by bharat-1809** [comment]
Hi @KABILAN235 
It was a pretty notorious bug, thanks for the pull request 👍🏻 . I am glad that you are starting your open source journey by contributing to our package.

Just some things to do before the PR can be merged:
- You need to update the golden files by running: `flutter test --update-goldens` this is necessary as the change affects the appearance and the tests may fail.
-  Analyze the project using `flutter analyze .`
- Format the project using `flutter format .`

The above points are necessary for the tests to pass. Ping me if you need any help.

Thanks :)

**Comment by bharat-1809** [comment]
@all-contributors please add @KABILAN235 for bug and code

**Comment by bharat-1809** [comment]
@all-contributors please add @KABILAN235 for bug and code

**Review by bharat-1809 — CHANGES_REQUESTED** [review]
Golden tests failing. I request you to update the golden files by running `flutter test --update-goldens`.
Rest LGTM 👍🏻

**Review by bharat-1809 — APPROVED** [review]
LGTM

**Pull request merged**
